trigger:
  - master

schedules:
  - cron: '0 20 * * *'
    displayName: Daily Check
    branches:
      include:
        - master
    always: 'true'

variables: 
  versionNano: "1809"

resources:
  repositories:
    - repository: templates
      type: github
      name: Justin-DynamicD/azure_pipeline-templates
      endpoint: GitHub

jobs:
  - job: getVersions
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: PowerShell@2
        displayName: Download Required Scripts
        inputs:
          targetType: inline
          script: |
            write-output "cloning: $env:TEMPLATE_REPO_URL"
            git clone $env:TEMPLATE_REPO_URL
            ls .\$($env:TEMPLATE_REPO_NAME)\
            cp .\$($env:TEMPLATE_REPO_NAME)\$($env:TEMPLATE_FILE) .\
            remove-item .\$env:TEMPLATE_REPO_NAME\ -Recurse -force -Confirm:$false
        env:
          TEMPLATE_REPO_URL: https://github.com/Justin-DynamicD/docker-windows-prometheus
          TEMPLATE_REPO_NAME: azure_pipeline-templates
          TEMPLATE_FILE: scripts\compare-gitreleases.ps1

      - task: PowerShell@2
        name: checkPrometheus
        displayName: Check available Prometheus version
        inputs:
          filepath: compare-gitreleases.ps1
          arguments: -SourceGithubOwner prometheus -SourceGithubRepo prometheus -TargetGithubOwner Justin-DynamicD -TargetGithubRepo docker-windows-prometheus

      - task: PowerShell@2
        name: generateBA
        displayName: Generate Build_Arguments
        inputs:
          targetType: inline
          script: |
            $myargs = "--build-arg VERSIONNANO=$(versionNano) --build-arg VERSIONPROMETHEUS=$(releaseLatest)"
            write-output $myargs
            write-output "##vso[task.setvariable variable=buildArguments;isOutput=true]$myargs"

  - template: docker_container.yml@templates
    parameters:
      Container_Name: winprometheus
      Container_Version: $[ dependencies.getVersions.outputs['checkPrometheus.releaseLatest'] ]
      Build_Arguments: $[ dependencies.getVersions.outputs['generateBA.buildArguments'] ]
      dependsOn: getVersions
      NewBuild: $[ dependencies.getJenkinsVer.outputs['checkPrometheus.newBuild'] ]
      Pool: 'windows-2019'
